/**
  ******************************************************************************
  * @file           : res_mgr.h
  * @brief          : Header for res_mgr.c file.
  *                   This file contains the common defines of the application.
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2023 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  *
  ******************************************************************************
  */

/* Define to prevent recursive inclusion -------------------------------------*/
#ifndef RES_MGR_H
#define RES_MGR_H

#ifdef __cplusplus
extern "C" {
#endif

/* Includes ------------------------------------------------------------------*/
#include "stdio.h"
#include "string.h"
#include "stm32mp2xx_hal.h"

/* Exported macros -----------------------------------------------------------*/
#define TRUE 1
#define FALSE 0


#define RESMGR_CIDCFGR_CFEN_Pos      (0U)
#define RESMGR_CIDCFGR_CFEN_Msk      (0x1U << RESMGR_CIDCFGR_CFEN_Pos)        /*!< 0x00000001 */
#define RESMGR_CIDCFGR_CFEN          RESMGR_CIDCFGR_CFEN_Msk

#define RESMGR_CIDCFGR_SEMEN_Pos     (1U)
#define RESMGR_CIDCFGR_SEMEN_Msk     (0x1U << RESMGR_CIDCFGR_SEMEN_Pos)       /*!< 0x00000002 */
#define RESMGR_CIDCFGR_SEMEN         RESMGR_CIDCFGR_SEMEN_Msk

#define RESMGR_CIDCFGR_SCID_Pos      (4U)
#define RESMGR_CIDCFGR_SCID_Msk      (0x7U << RESMGR_CIDCFGR_SCID_Pos)        /*!< 0x00000070 */
#define RESMGR_CIDCFGR_SCID          RESMGR_CIDCFGR_SCID_Msk
#define RESMGR_CIDCFGR_SCID0         (0x0U << RESMGR_CIDCFGR_SCID_Pos)        /*!< 0x00000000 */
#define RESMGR_CIDCFGR_SCID1         (0x1U << RESMGR_CIDCFGR_SCID_Pos)        /*!< 0x00000010 */
#define RESMGR_CIDCFGR_SCID2         (0x2U << RESMGR_CIDCFGR_SCID_Pos)        /*!< 0x00000020 */
#define RESMGR_CIDCFGR_SCID3         (0x3U << RESMGR_CIDCFGR_SCID_Pos)        /*!< 0x00000030 */
#define RESMGR_CIDCFGR_SCID4         (0x4U << RESMGR_CIDCFGR_SCID_Pos)        /*!< 0x00000040 */
#define RESMGR_CIDCFGR_SCID5         (0x5U << RESMGR_CIDCFGR_SCID_Pos)        /*!< 0x00000050 */
#define RESMGR_CIDCFGR_SCID6         (0x6U << RESMGR_CIDCFGR_SCID_Pos)        /*!< 0x00000060 */
#define RESMGR_CIDCFGR_SCID7         (0x7U << RESMGR_CIDCFGR_SCID_Pos)        /*!< 0x00000070 */

#define RESMGR_CIDCFGR_SEMWL_Pos     (16U)
#define RESMGR_CIDCFGR_SEMWL_Msk     (0xFFU << RESMGR_CIDCFGR_SEMWL_Pos)      /*!< 0x00FF0000 */
#define RESMGR_CIDCFGR_SEMWL         RESMGR_CIDCFGR_SEMWL_Msk
#define RESMGR_CIDCFGR_SEMWLC0       (0x1U << RESMGR_CIDCFGR_SEMWL_Pos)       /*!< 0x00010000 */
#define RESMGR_CIDCFGR_SEMWLC1       (0x2U << RESMGR_CIDCFGR_SEMWL_Pos)       /*!< 0x00020000 */
#define RESMGR_CIDCFGR_SEMWLC2       (0x4U << RESMGR_CIDCFGR_SEMWL_Pos)       /*!< 0x00040000 */
#define RESMGR_CIDCFGR_SEMWLC3       (0x8U << RESMGR_CIDCFGR_SEMWL_Pos)       /*!< 0x00080000 */
#define RESMGR_CIDCFGR_SEMWLC4       (0x10U << RESMGR_CIDCFGR_SEMWL_Pos)      /*!< 0x00100000 */
#define RESMGR_CIDCFGR_SEMWLC5       (0x20U << RESMGR_CIDCFGR_SEMWL_Pos)      /*!< 0x00200000 */
#define RESMGR_CIDCFGR_SEMWLC6       (0x40U << RESMGR_CIDCFGR_SEMWL_Pos)      /*!< 0x00400000 */
#define RESMGR_CIDCFGR_SEMWLC7       (0x80U << RESMGR_CIDCFGR_SEMWL_Pos)      /*!< 0x00800000 */


#define RESMGR_SEMCR_SEMMUTEX_Pos    (0U)
#define RESMGR_SEMCR_SEMMUTEX_Msk    (0x1U << RESMGR_SEMCR_SEMMUTEX_Pos)      /*!< 0x00000001 */
#define RESMGR_SEMCR_SEMMUTEX        RESMGR_SEMCR_SEMMUTEX_Msk

#define RESMGR_SEMCR_SEMCID_Pos      (4U)
#define RESMGR_SEMCR_SEMCID_Msk      (0x7U << RESMGR_SEMCR_SEMCID_Pos)        /*!< 0x00000070 */
#define RESMGR_SEMCR_SEMCID          RESMGR_SEMCR_SEMCID_Msk
#define RESMGR_SEMCR_SEMCID0         (0x0U << RESMGR_SEMCR_SEMCID_Pos)        /*!< 0x00000000 */
#define RESMGR_SEMCR_SEMCID1         (0x1U << RESMGR_SEMCR_SEMCID_Pos)        /*!< 0x00000010 */
#define RESMGR_SEMCR_SEMCID2         (0x2U << RESMGR_SEMCR_SEMCID_Pos)        /*!< 0x00000020 */
#define RESMGR_SEMCR_SEMCID3         (0x3U << RESMGR_SEMCR_SEMCID_Pos)        /*!< 0x00000030 */
#define RESMGR_SEMCR_SEMCID4         (0x4U << RESMGR_SEMCR_SEMCID_Pos)        /*!< 0x00000040 */
#define RESMGR_SEMCR_SEMCID5         (0x5U << RESMGR_SEMCR_SEMCID_Pos)        /*!< 0x00000050 */
#define RESMGR_SEMCR_SEMCID6         (0x6U << RESMGR_SEMCR_SEMCID_Pos)        /*!< 0x00000060 */
#define RESMGR_SEMCR_SEMCID7         (0x7U << RESMGR_SEMCR_SEMCID_Pos)        /*!< 0x00000070 */

#define CPU_SECURE                      1
#define CPU_UNSECURE                    0

#define PRIVILEGED              0x01u   /* Privileged access */
#define UNPRIVILEGED            0x00u   /* Unprivileged access */

#define THREAD_MODE_PRIVILEGED      0x00   /* Thread mode has privileged access */
#define THREAD_MODE_UNPRIVILEGED    0x01   /* Thread mode has unprivileged access */

/* RIFSC ID */
#if  defined(STM32MP257Cxx) || defined(STM32MP257Fxx) || defined(STM32MP25xx)
#define STM32MP25_RIFSC_TIM1_ID   			  0
#define STM32MP25_RIFSC_TIM2_ID   			  1
#define STM32MP25_RIFSC_TIM3_ID   			  2
#define STM32MP25_RIFSC_TIM4_ID   			  3
#define STM32MP25_RIFSC_TIM5_ID   			  4
#define STM32MP25_RIFSC_TIM6_ID   			  5
#define STM32MP25_RIFSC_TIM7_ID   			  6
#define STM32MP25_RIFSC_TIM8_ID   			  7
#define STM32MP25_RIFSC_TIM10_ID  			  8
#define STM32MP25_RIFSC_TIM11_ID  			  9
#define STM32MP25_RIFSC_TIM12_ID  			  10
#define STM32MP25_RIFSC_TIM13_ID  			  11
#define STM32MP25_RIFSC_TIM14_ID  			  12
#define STM32MP25_RIFSC_TIM15_ID  			  13
#define STM32MP25_RIFSC_TIM16_ID  			  14
#define STM32MP25_RIFSC_TIM17_ID  			  15
#define STM32MP25_RIFSC_TIM20_ID  			  16
#define STM32MP25_RIFSC_LPTIM1_ID 			  17
#define STM32MP25_RIFSC_LPTIM2_ID 			  18
#define STM32MP25_RIFSC_LPTIM3_ID 			  19
#define STM32MP25_RIFSC_LPTIM4_ID 			  20
#define STM32MP25_RIFSC_LPTIM5_ID 			  21
#define STM32MP25_RIFSC_SPI1_ID   			  22
#define STM32MP25_RIFSC_SPI2_ID   			  23
#define STM32MP25_RIFSC_SPI3_ID   			  24
#define STM32MP25_RIFSC_SPI4_ID   			  25
#define STM32MP25_RIFSC_SPI5_ID   			  26
#define STM32MP25_RIFSC_SPI6_ID   			  27
#define STM32MP25_RIFSC_SPI7_ID				  28
#define STM32MP25_RIFSC_SPI8_ID   			  29
#define STM32MP25_RIFSC_SPDIFRX_ID 		      30
#define STM32MP25_RIFSC_USART1_ID  			  31
#define STM32MP25_RIFSC_USART2_ID		      32
#define STM32MP25_RIFSC_USART3_ID 			  33
#define STM32MP25_RIFSC_UART4_ID 		      34
#define STM32MP25_RIFSC_UART5_ID  			  35
#define STM32MP25_RIFSC_USART6_ID 			  36
#define STM32MP25_RIFSC_UART7_ID  			  37
#define STM32MP25_RIFSC_UART8_ID  			  38
#define STM32MP25_RIFSC_UART9_ID    		  39
#define STM32MP25_RIFSC_LPUART1_ID   		  40
#define STM32MP25_RIFSC_I2C1_ID   			  41
#define STM32MP25_RIFSC_I2C2_ID   			  42
#define STM32MP25_RIFSC_I2C3_ID   			  43
#define STM32MP25_RIFSC_I2C4_ID   			  44
#define STM32MP25_RIFSC_I2C5_ID   			  45
#define STM32MP25_RIFSC_I2C6_ID   			  46
#define STM32MP25_RIFSC_I2C7_ID   			  47
#define STM32MP25_RIFSC_I2C8_ID   			  48
#define STM32MP25_RIFSC_SAI1_ID   			  49
#define STM32MP25_RIFSC_SAI2_ID   			  50
#define STM32MP25_RIFSC_SAI3_ID   			  51
#define STM32MP25_RIFSC_SAI4_ID   			  52
#define STM32MP25_RIFSC_MDF1_ID   			  54
#define STM32MP25_RIFSC_ADF1_ID  		      55
#define STM32MP25_RIFSC_FDCAN_ID 		      56
#define STM32MP25_RIFSC_HDP_ID   		      57
#define STM32MP25_RIFSC_ADC12_ID  			  58
#define STM32MP25_RIFSC_ADC3_ID   			  59
#define STM32MP25_RIFSC_ETH1_ID  			  60
#define STM32MP25_RIFSC_ETH2_ID   			  61
#define STM32MP25_RIFSC_USBH_ID   			  63
#define STM32MP25_RIFSC_USB3DR_ID 			  66
#define STM32MP25_RIFSC_COMBOPHY_ID 		  67
#define STM32MP25_RIFSC_PCIE_ID   			  68
#define STM32MP25_RIFSC_UCPD1_ID  			  69
#define STM32MP25_RIFSC_ETHSW_DEIP_ID         70
#define STM32MP25_RIFSC_ETHSW_ACM_CFG_ID      71
#define STM32MP25_RIFSC_ETHSW_ACM_MSGBUF_ID   72
#define STM32MP25_RIFSC_STGEN_ID  		  	  73
#define STM32MP25_RIFSC_OCTOSPI1_ID	   	 	  74
#define STM32MP25_RIFSC_OCTOSPI2_ID 	 	  75
#define STM32MP25_RIFSC_SDMMC1_ID 		 	  76
#define STM32MP25_RIFSC_SDMMC2_ID 			  77
#define STM32MP25_RIFSC_SDMMC3_ID 			  78
#define STM32MP25_RIFSC_GPU_ID    			  79
#define STM32MP25_RIFSC_LTDC_CMN_ID 		  80
#define STM32MP25_RIFSC_DSI_CMN_ID  		  81
#define STM32MP25_RIFSC_LVDS_ID  	    	  84
#define STM32MP25_RIFSC_CSI_ID    			  86
#define STM32MP25_RIFSC_DCMIPP_ID 			  87
#define STM32MP25_RIFSC_DCMI_PSSI_ID    	  88
#define STM32MP25_RIFSC_VDEC_ID  	    	  89
#define STM32MP25_RIFSC_VENC_ID   			  90
#define STM32MP25_RIFSC_RNG_ID    			  92
#define STM32MP25_RIFSC_PKA_ID    			  93
#define STM32MP25_RIFSC_SAES_ID   			  94
#define STM32MP25_RIFSC_HASH_ID   			  95
#define STM32MP25_RIFSC_CRYP1_ID  			  96
#define STM32MP25_RIFSC_CRYP2_ID  			  97
#define STM32MP25_RIFSC_IWDG1_ID  			  98
#define STM32MP25_RIFSC_IWDG2_ID  			  99
#define STM32MP25_RIFSC_IWDG3_ID  			  100
#define STM32MP25_RIFSC_IWDG4_ID  			  101
#define STM32MP25_RIFSC_IWDG5_ID  			  102
#define STM32MP25_RIFSC_WWDG1_ID  		 	  103
#define STM32MP25_RIFSC_WWDG2_ID  			  104
#define STM32MP25_RIFSC_VREFBUF_ID 		 	  106
#define STM32MP25_RIFSC_DTS_ID   	    	  107
#define STM32MP25_RIFSC_RAMCFG_ID 			  108
#define STM32MP25_RIFSC_CRC_ID    			  109
#define STM32MP25_RIFSC_SERC_ID  	 		  110
#define STM32MP25_RIFSC_OCTOSPIM_ID	    	  111
#define STM32MP25_RIFSC_GICV2M_ID 			  112
#define STM32MP25_RIFSC_I3C1_ID   			  114
#define STM32MP25_RIFSC_I3C2_ID   			  115
#define STM32MP25_RIFSC_I3C3_ID     		  116
#define STM32MP25_RIFSC_I3C4_ID         	  117
#define STM32MP25_RIFSC_ICACHE_DCACHE_ID	  118
#define STM32MP25_RIFSC_LTDC_L0L1_ID  		  119
#define STM32MP25_RIFSC_LTDC_L2_ID     	      120
#define STM32MP25_RIFSC_LTDC_ROT_ID           121
#define STM32MP25_RIFSC_DSI_TRIG_ID           122
#define STM32MP25_RIFSC_DSI_RDFIFO_ID  	      123
#define STM32MP25_RIFSC_OTFDEC1_ID     	      125
#define STM32MP25_RIFSC_OTFDEC2_ID            126
#define STM32MP25_RIFSC_IAC_ID      	      127


#define RESMGR_RIFSC_TIM1_ID 			 STM32MP25_RIFSC_TIM1_ID
#define RESMGR_RIFSC_TIM2_ID    		 STM32MP25_RIFSC_TIM2_ID
#define RESMGR_RIFSC_TIM3_ID    		 STM32MP25_RIFSC_TIM3_ID
#define RESMGR_RIFSC_TIM4_ID    		 STM32MP25_RIFSC_TIM4_ID
#define RESMGR_RIFSC_TIM5_ID    		 STM32MP25_RIFSC_TIM5_ID
#define RESMGR_RIFSC_TIM6_ID    		 STM32MP25_RIFSC_TIM6_ID
#define RESMGR_RIFSC_TIM7_ID    		 STM32MP25_RIFSC_TIM7_ID
#define RESMGR_RIFSC_TIM8_ID     		 STM32MP25_RIFSC_TIM8_ID
#define RESMGR_RIFSC_TIM10_ID   		 STM32MP25_RIFSC_TIM10_ID
#define RESMGR_RIFSC_TIM11_ID   		 STM32MP25_RIFSC_TIM11_ID
#define RESMGR_RIFSC_TIM12_ID    		 STM32MP25_RIFSC_TIM12_ID
#define RESMGR_RIFSC_TIM13_ID			 STM32MP25_RIFSC_TIM13_ID
#define RESMGR_RIFSC_TIM14_ID   		 STM32MP25_RIFSC_TIM14_ID
#define RESMGR_RIFSC_TIM15_ID   		 STM32MP25_RIFSC_TIM15_ID
#define RESMGR_RIFSC_TIM16_ID    		 STM32MP25_RIFSC_TIM16_ID
#define RESMGR_RIFSC_TIM17_ID  		     STM32MP25_RIFSC_TIM17_ID
#define RESMGR_RIFSC_TIM20_ID    		 STM32MP25_RIFSC_TIM20_ID
#define RESMGR_RIFSC_LPTIM1_ID  		 STM32MP25_RIFSC_LPTIM1_ID
#define RESMGR_RIFSC_LPTIM2_ID  		 STM32MP25_RIFSC_LPTIM2_ID
#define RESMGR_RIFSC_LPTIM3_ID  		 STM32MP25_RIFSC_LPTIM3_ID
#define RESMGR_RIFSC_LPTIM4_ID  		 STM32MP25_RIFSC_LPTIM4_ID
#define RESMGR_RIFSC_LPTIM5_ID  		 STM32MP25_RIFSC_LPTIM5_ID
#define RESMGR_RIFSC_SPI1_ID    		 STM32MP25_RIFSC_SPI1_ID
#define RESMGR_RIFSC_SPI2_ID    		 STM32MP25_RIFSC_SPI2_ID
#define RESMGR_RIFSC_SPI3_ID    		 STM32MP25_RIFSC_SPI3_ID
#define RESMGR_RIFSC_SPI4_ID    		 STM32MP25_RIFSC_SPI4_ID
#define RESMGR_RIFSC_SPI5_ID    		 STM32MP25_RIFSC_SPI5_ID
#define RESMGR_RIFSC_SPI6_ID    		 STM32MP25_RIFSC_SPI6_ID
#define RESMGR_RIFSC_SPI7_ID    		 STM32MP25_RIFSC_SPI7_ID
#define RESMGR_RIFSC_SPI8_ID    		 STM32MP25_RIFSC_SPI8_ID
#define RESMGR_RIFSC_SPDIFRX_ID 		 STM32MP25_RIFSC_SPDIFRX_ID
#define RESMGR_RIFSC_USART1_ID  		 STM32MP25_RIFSC_USART1_ID
#define RESMGR_RIFSC_USART2_ID  		 STM32MP25_RIFSC_USART2_ID
#define RESMGR_RIFSC_USART3_ID  		 STM32MP25_RIFSC_USART3_ID
#define RESMGR_RIFSC_UART4_ID   		 STM32MP25_RIFSC_UART4_ID
#define RESMGR_RIFSC_UART5_ID   		 STM32MP25_RIFSC_UART5_ID
#define RESMGR_RIFSC_USART6_ID  		 STM32MP25_RIFSC_USART6_ID
#define RESMGR_RIFSC_UART7_ID   		 STM32MP25_RIFSC_UART7_ID
#define RESMGR_RIFSC_UART8_ID   		 STM32MP25_RIFSC_UART8_ID
#define RESMGR_RIFSC_UART9_ID   		 STM32MP25_RIFSC_UART9_ID
#define RESMGR_RIFSC_LPUART1_ID 		 STM32MP25_RIFSC_LPUART1_ID
#define RESMGR_RIFSC_I2C1_ID    		 STM32MP25_RIFSC_I2C1_ID
#define RESMGR_RIFSC_I2C2_ID   		     STM32MP25_RIFSC_I2C2_ID
#define RESMGR_RIFSC_I2C3_ID   			 STM32MP25_RIFSC_I2C3_ID
#define RESMGR_RIFSC_I2C4_ID    		 STM32MP25_RIFSC_I2C4_ID
#define RESMGR_RIFSC_I2C5_ID    		 STM32MP25_RIFSC_I2C5_ID
#define RESMGR_RIFSC_I2C6_ID    		 STM32MP25_RIFSC_I2C6_ID
#define RESMGR_RIFSC_I2C7_ID    		 STM32MP25_RIFSC_I2C7_ID
#define RESMGR_RIFSC_I2C8_ID    		 STM32MP25_RIFSC_I2C8_ID
#define RESMGR_RIFSC_SAI1_ID    		 STM32MP25_RIFSC_SAI1_ID
#define RESMGR_RIFSC_SAI2_ID    		 STM32MP25_RIFSC_SAI2_ID
#define RESMGR_RIFSC_SAI3_ID    		 STM32MP25_RIFSC_SAI3_ID
#define RESMGR_RIFSC_SAI4_ID    		 STM32MP25_RIFSC_SAI4_ID
#define RESMGR_RIFSC_MDF1_ID    		 STM32MP25_RIFSC_MDF1_ID
#define RESMGR_RIFSC_ADF1_ID    		 STM32MP25_RIFSC_ADF1_ID
#define RESMGR_RIFSC_FDCAN_ID   		 STM32MP25_RIFSC_FDCAN_ID
#define RESMGR_RIFSC_HDP_ID     		 STM32MP25_RIFSC_HDP_ID
#define RESMGR_RIFSC_ADC12_ID   		 STM32MP25_RIFSC_ADC12_ID
#define RESMGR_RIFSC_ADC3_ID    		 STM32MP25_RIFSC_ADC3_ID
#define RESMGR_RIFSC_ETH1_ID    		 STM32MP25_RIFSC_ETH1_ID
#define RESMGR_RIFSC_ETH2_ID    		 STM32MP25_RIFSC_ETH2_ID
#define RESMGR_RIFSC_USBH_ID    		 STM32MP25_RIFSC_USBH_ID
#define RESMGR_RIFSC_USB3DR_ID  		 STM32MP25_RIFSC_USB3DR_ID
#define RESMGR_RIFSC_COMBOPHY_ID 		 STM32MP25_RIFSC_COMBOPHY_ID
#define RESMGR_RIFSC_PCIE_ID     		 STM32MP25_RIFSC_PCIE_ID
#define RESMGR_RIFSC_UCPD1_ID   		 STM32MP25_RIFSC_UCPD1_ID
#define RESMGR_RIFSC_ETHSW_DEIP_ID  	 STM32MP25_RIFSC_ETHSW_DEIP_ID
#define RESMGR_RIFSC_ETHSW_ACM_CFG_ID 	 STM32MP25_RIFSC_ETHSW_ACM_CFG_ID
#define RESMGR_RIFSC_ETHSW_ACM_MSGBUF_ID STM32MP25_RIFSC_ETHSW_ACM_MSGBUF_ID
#define RESMGR_RIFSC_STGEN_ID   		 STM32MP25_RIFSC_STGEN_ID
#define RESMGR_RIFSC_OCTOSPI1_ID   		 STM32MP25_RIFSC_OCTOSPI1_ID
#define RESMGR_RIFSC_OCTOSPI2_ID  		 STM32MP25_RIFSC_OCTOSPI2_ID
#define RESMGR_RIFSC_SDMMC1_ID  		 STM32MP25_RIFSC_SDMMC1_ID
#define RESMGR_RIFSC_SDMMC2_ID  		 STM32MP25_RIFSC_SDMMC2_ID
#define RESMGR_RIFSC_SDMMC3_ID  		 STM32MP25_RIFSC_SDMMC3_ID
#define RESMGR_RIFSC_GPU_ID     		 STM32MP25_RIFSC_GPU_ID
#define RESMGR_RIFSC_LTDC_CMN_ID  		 STM32MP25_RIFSC_LTDC_CMN_ID
#define RESMGR_RIFSC_DSI_CMN_ID  	 	 STM32MP25_RIFSC_DSI_CMN_ID
#define RESMGR_RIFSC_LVDS_ID    		 STM32MP25_RIFSC_LVDS_ID
#define RESMGR_RIFSC_CSI_ID     		 STM32MP25_RIFSC_CSI_ID
#define RESMGR_RIFSC_DCMIPP_ID  		 STM32MP25_RIFSC_DCMIPP_ID
#define RESMGR_RIFSC_DCMI_PSSI_ID  	 	 STM32MP25_RIFSC_DCMI_PSSI_ID
#define RESMGR_RIFSC_VDEC_ID    		 STM32MP25_RIFSC_VDEC_ID
#define RESMGR_RIFSC_VENC_ID    		 STM32MP25_RIFSC_VENC_ID
#define RESMGR_RIFSC_RNG_ID     		 STM32MP25_RIFSC_RNG_ID
#define RESMGR_RIFSC_PKA_ID     		 STM32MP25_RIFSC_PKA_ID
#define RESMGR_RIFSC_SAES_ID   		     STM32MP25_RIFSC_SAES_ID
#define RESMGR_RIFSC_HASH_ID    		 STM32MP25_RIFSC_HASH_ID
#define RESMGR_RIFSC_CRYP1_ID   		 STM32MP25_RIFSC_CRYP1_ID
#define RESMGR_RIFSC_CRYP2_ID   		 STM32MP25_RIFSC_CRYP2_ID
#define RESMGR_RIFSC_IWDG1_ID   		 STM32MP25_RIFSC_IWDG1_ID
#define RESMGR_RIFSC_IWDG2_ID   		 STM32MP25_RIFSC_IWDG2_ID
#define RESMGR_RIFSC_IWDG3_ID   		 STM32MP25_RIFSC_IWDG3_ID
#define RESMGR_RIFSC_IWDG4_ID   		 STM32MP25_RIFSC_IWDG4_ID
#define RESMGR_RIFSC_IWDG5_ID   		 STM32MP25_RIFSC_IWDG5_ID
#define RESMGR_RIFSC_WWDG1_ID   		 STM32MP25_RIFSC_WWDG1_ID
#define RESMGR_RIFSC_WWDG2_ID   		 STM32MP25_RIFSC_WWDG2_ID
#define RESMGR_RIFSC_VREFBUF_ID 		 STM32MP25_RIFSC_VREFBUF_ID
#define RESMGR_RIFSC_DTS_ID     		 STM32MP25_RIFSC_DTS_ID
#define RESMGR_RIFSC_RAMCFG_ID  		 STM32MP25_RIFSC_RAMCFG_ID
#define RESMGR_RIFSC_CRC_ID     		 STM32MP25_RIFSC_CRC_ID
#define RESMGR_RIFSC_SERC_ID    		 STM32MP25_RIFSC_SERC_ID
#define RESMGR_RIFSC_OCTOSPIM_ID		 STM32MP25_RIFSC_OCTOSPIM_ID
#define RESMGR_RIFSC_GICV2M_ID  		 STM32MP25_RIFSC_GICV2M_ID
#define RESMGR_RIFSC_I3C1_ID    		 STM32MP25_RIFSC_I3C1_ID
#define RESMGR_RIFSC_I3C2_ID    		 STM32MP25_RIFSC_I3C2_ID
#define RESMGR_RIFSC_I3C3_ID    		 STM32MP25_RIFSC_I3C3_ID
#define RESMGR_RIFSC_I3C4_ID    		 STM32MP25_RIFSC_I3C4_ID
#define RESMGR_RIFSC_ICACHE_DCACHE_ID 	 STM32MP25_RIFSC_ICACHE_DCACHE_ID
#define RESMGR_RIFSC_LTDC_L0L1_ID     	 STM32MP25_RIFSC_LTDC_L0L1_ID
#define RESMGR_RIFSC_LTDC_L2_ID   		 STM32MP25_RIFSC_LTDC_L2_ID
#define RESMGR_RIFSC_LTDC_ROT_ID  		 STM32MP25_RIFSC_LTDC_ROT_ID
#define RESMGR_RIFSC_DSI_TRIG_ID  		 STM32MP25_RIFSC_DSI_TRIG_ID
#define RESMGR_RIFSC_DSI_RDFIFO_ID 		 STM32MP25_RIFSC_DSI_RDFIFO_ID
#define RESMGR_RIFSC_OTFDEC1_ID   		 STM32MP25_RIFSC_OTFDEC1_ID
#define RESMGR_RIFSC_OTFDEC2_ID   		 STM32MP25_RIFSC_OTFDEC2_ID
#define RESMGR_RIFSC_IAC_ID      		 STM32MP25_RIFSC_IAC_ID
#endif

#define RESMGR_RIFSC_RIFSC_ID_MAX   127

typedef enum
{
  RESMGR_RESOURCE_RIFSC,
  RESMGR_RESOURCE_RIF_PWR_WIO,
  RESMGR_RESOURCE_RIF_RCC,
  RESMGR_RESOURCE_RIF_GPIOA,
  RESMGR_RESOURCE_RIF_GPIOB,
  RESMGR_RESOURCE_RIF_GPIOC,
  RESMGR_RESOURCE_RIF_GPIOD,
  RESMGR_RESOURCE_RIF_GPIOE,
  RESMGR_RESOURCE_RIF_GPIOF,
  RESMGR_RESOURCE_RIF_GPIOG,
  RESMGR_RESOURCE_RIF_GPIOH,
  RESMGR_RESOURCE_RIF_GPIOI,
  RESMGR_RESOURCE_RIF_GPIOJ,
  RESMGR_RESOURCE_RIF_GPIOK,
  RESMGR_RESOURCE_RIF_GPIOZ,
  RESMGR_RESOURCE_RIF_FMC,
  RESMGR_RESOURCE_RIF_PWR,
  RESMGR_RESOURCE_RIF_RTC,
  RESMGR_RESOURCE_RIF_EXTI1,
  RESMGR_RESOURCE_RIF_EXTI2,
  RESMGR_RESOURCE_RIF_HPDMA1,
  RESMGR_RESOURCE_RIF_HPDMA2,
  RESMGR_RESOURCE_RIF_HPDMA3,
  RESMGR_RESOURCE_MAX,
} ResMgr_Res_Type_t;


 /* Internal types ------------------------------------------------------------*/
typedef enum
{
  RESMGR_COMP_CID_ONLY,
  RESMGR_COM_CID_WITH_SEMCR
} ResMgr_CID_type_t;
typedef struct
{
  __IO uint32_t CIDCFGR;
  __IO uint32_t SEMCR;
} ResMgr_Comp_t;
typedef struct
{
  ResMgr_Comp_t *cid_base;
  __IO uint32_t *priv_base;
  __IO uint32_t *sec_base;
  __IO uint32_t *CIDCFGR;
  __IO uint32_t *SEMCR;
  ResMgr_CID_type_t cid_type;
  ResMgr_Res_Type_t res_type;
  uint32_t max_res_num;
} ResMgr_data_info_t;

/* Exported types ------------------------------------------------------------*/
#define RESMGR_PWR_RESOURCE(x)       (x)
#define RESMGR_RCC_RESOURCE(x)       (x)
#define RESMGR_GPIO_PIN(x)           (x)
#define RESMGR_PWR_RESOURCE_WIO(x)   (x-1)
#define RESMGR_HPDMA_CHANNEL(x)      (x)
#define RESMGR_EXTI_RESOURCE(x)      (x)



#define RESMGR_RTC_PROT_BITS_POS(__RES_NUM__)       (__RES_NUM__ < 3 ? __RES_NUM__ : (__RES_NUM__ + 9))


#define RESMGR_RIFSC_PWR_RSC_NB  		NON_SHAREABLE_RESOURCE_NB
#define RESMGR_RIFSC_PWR_WIO_RSC_NB     SHAREABLE_RESOURCE_NB
/* Maximum Resource for each GPIO Port */
#define RESMGR_RIFSC_GPIO_RSC_NB        15
#define RESMGR_RIFSC_HPDMA_RSC_NB       15
#define RESMGR_RIFSC_RCC_RSC_NB         113
#define RESMGR_RIFSC_EXTI1_RSC_NB       EXTI1_LINE_NB
#define RESMGR_RIFSC_EXTI2_RSC_NB       EXTI2_LINE_NB
#define RESMGR_RIFSC_FMC_RSC_NB         5
#define RESMGR_RIFSC_RTC_RSC_NB         5



typedef enum
{
  RESMGR_STATUS_ACCESS_OK              = 0x00U,
  RESMGR_STATUS_NPRIV_ACCESS_ERROR     = 0x01U,
  RESMGR_STATUS_NSEC_ACCESS_ERROR      = 0x02U,
  RESMGR_STATUS_SCID_ACCESS_ERROR      = 0x03U,
  RESMGR_STATUS_CID_WL_ACCESS_ERROR    = 0x04U,
  RESMGR_STATUS_SEM_ACCESS_ERROR       = 0x05U,
  RESMGR_STATUS_ACCESS_ERROR           = 0x06U,
  RESMGR_STATUS_ERROR_NONE             = 0x07U,
  RESMGR_STATUS_RES_TYP_ERROR          = 0x08U,
  RESMGR_STATUS_RES_NUM_ERROR          = 0x09U
} ResMgr_Status_t;

typedef enum
{
  RESMGR_SEM_STATUS_TAKEN            = 0x00U,
  RESMGR_SEM_STATUS_RELEASED         = 0x01U,
  RESMGR_SEM_STATUS_ERROR            = 0x02U
} ResMgr_Sem_Status_t;




/* Private macros ------------------------------------------------------------*/
/** @defgroup RESMGR_Private_Macros RESMGR Private Macros
  * @{
  */
#define IS_RESMGR_RES_TYPE(__TYPE__)     ((ResMgr_Res_Type_t )(__TYPE__) < (ResMgr_Res_Type_t) RESMGR_RESOURCE_MAX)

#define IS_RESMGR_RIFSC_RSC(__NUM__)     ((__NUM__) <= RESMGR_RIFSC_RIFSC_ID_MAX)

#define IS_RESMGR_PWR_RSC(__NUM__)       ((__NUM__) < RESMGR_RIFSC_PWR_RSC_NB)

#define IS_RESMGR_PWR_RSC_WIO(__NUM__)   ((__NUM__) < RESMGR_RIFSC_PWR_WIO_RSC_NB)

#define IS_RESMGR_RCC_RSC(__NUM__)       ((__NUM__) <= RESMGR_RIFSC_RCC_RSC_NB)

#define IS_RESMGR_GPIO_RSC(__NUM__)      ((__NUM__) <= RESMGR_RIFSC_GPIO_RSC_NB)

#define IS_RESMGR_EXTI1_RSC(__NUM__)     ((__NUM__) <  RESMGR_RIFSC_EXTI1_RSC_NB)

#define IS_RESMGR_EXTI2_RSC(__NUM__)     ((__NUM__) < RESMGR_RIFSC_EXTI2_RSC_NB)

#define IS_RESMGR_FMC_RSC(__NUM__)       ((__NUM__) <= RESMGR_RIFSC_FMC_RSC_NB)

#define IS_RESMGR_HPDMA_RSC(__NUM__)     ((__NUM__) <= RESMGR_RIFSC_HPDMA_RSC_NB)

#define IS_RESMGR_RTC_RSC(__NUM__)     ((__NUM__) <= RESMGR_RIFSC_RTC_RSC_NB)

/* Exported functions ------------------------------------------------------- */
ResMgr_Status_t ResMgr_Request(ResMgr_Res_Type_t res_type, uint8_t res_num);
ResMgr_Status_t ResMgr_Release(ResMgr_Res_Type_t res_type, uint8_t res_num);

#ifdef __cplusplus
}
#endif

#endif /* RES_MGR_H */
